kind: Pod
apiVersion: v1
metadata:
  name: new-nginx-pod
  labels:
     app: mynginx
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim2
