apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-store
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://us-east-2a/vol-02fe14ab9191827c9
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  volumeMode: Filesystem
