apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mynginx
  name: pvc-web-store
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc
  volumeMode: Filesystem
  volumeName: pv-web-store
